/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view;

import common.TrafficLightState;
import common.NetWrapper;
import java.awt.Graphics;
import viewGeneral.HelpDialog;
import viewGeneral.DisclaimerDialog;
import viewGeneral.AboutDialog;

/**
 * starts the graphical interface “ViewTrafficLight”, which will show the client
 * (traffic light).
 *
 * @author Roque Matheus Gomes Costa
 */
public class ViewTrafficLight extends javax.swing.JFrame {

    private NetWrapper netWrapper;

    /**
     * Creates new form Iniciar
     */
    public ViewTrafficLight() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanelTrafficLight = new javax.swing.JPanel();
        jLabelBackground = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        helpMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        disclaimerMenuItem = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTrafficLight.setBackground(new java.awt.Color(9, 12, 14));
        jPanelTrafficLight.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        getContentPane().add(jPanelTrafficLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 340, 110));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/FundoView1.png"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 520, 370));

        jMenu1.setText("File");

        jMenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/shut-down.png"))); // NOI18N
        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuExit);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Help");

        helpMenuItem.setText("Help");
        helpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(helpMenuItem);

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(aboutMenuItem);

        disclaimerMenuItem.setText("Disclaimer");
        disclaimerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disclaimerMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(disclaimerMenuItem);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        setSize(new java.awt.Dimension(505, 402));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method to Override paint of the interface
     *
     * @param g
     *
     */
    @Override
    public void paint(Graphics g) {

        super.paint(g);
        JDrawingTrafficLight drawingTrafficLight = new JDrawingTrafficLight(g);

        if (netWrapper != null) {

            drawingTrafficLight.ColorTrafficLight(netWrapper.getState());

        }

    }

    /**
     * Method that performs a new instance of the NetWrapper class by setting a
     * new state
     *
     *
     * @param state
     */
    public void setState(TrafficLightState state) {

        netWrapper = new NetWrapper(state);

    }

    private void disclaimerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disclaimerMenuItemActionPerformed

        DisclaimerDialog disclaimerDialog = new DisclaimerDialog(new javax.swing.JFrame(), true);
        disclaimerDialog.setVisible(true);

    }//GEN-LAST:event_disclaimerMenuItemActionPerformed

    private void helpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuItemActionPerformed

        HelpDialog helpDialog = new HelpDialog(new javax.swing.JFrame(), true);
        helpDialog.setVisible(true);

    }//GEN-LAST:event_helpMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed

        AboutDialog aboutDialog = new AboutDialog(new javax.swing.JFrame(), true);
        aboutDialog.setVisible(true);

    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed

        System.exit(0);

    }//GEN-LAST:event_jMenuExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem disclaimerMenuItem;
    private javax.swing.JMenuItem helpMenuItem;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanelTrafficLight;
    // End of variables declaration//GEN-END:variables
}
