/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server.view;
import viewGeneral.HelpDialog;
import viewGeneral.DisclaimerDialog;
import viewGeneral.AboutDialog;
import client.view.ViewTrafficLight;
/**
 *
 * @author Lucas Alkimim Chaves
 */
public class ViewTrafficLightStateConnections extends javax.swing.JFrame {

    private String messageJTextLogServer;
    /**
     * Creates new form Iniciar
     */
    public ViewTrafficLightStateConnections() {

        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        logServer = new javax.swing.JTextArea();
        jLabelBackground = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        helpMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        disclaimerMenuItem = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SERVER LOG");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 50));

        logServer.setColumns(20);
        logServer.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        logServer.setLineWrap(true);
        logServer.setRows(5);
        logServer.setToolTipText("");
        logServer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logServer.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        logServer.setEnabled(false);
        jScrollPane2.setViewportView(logServer);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 490, 260));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/FundoView1.png"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 670, 390));

        jMenu1.setText("File");

        jMenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/shut-down.png"))); // NOI18N
        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuExit);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Help");

        helpMenuItem.setText("Help");
        helpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(helpMenuItem);

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(aboutMenuItem);

        disclaimerMenuItem.setText("Disclaimer");
        disclaimerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disclaimerMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(disclaimerMenuItem);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        setSize(new java.awt.Dimension(627, 402));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void disclaimerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disclaimerMenuItemActionPerformed

        DisclaimerDialog disclaimerDialog = new DisclaimerDialog(new javax.swing.JFrame(), true);
        disclaimerDialog.setVisible(true);

    }//GEN-LAST:event_disclaimerMenuItemActionPerformed

    private void helpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuItemActionPerformed

        HelpDialog helpDialog = new HelpDialog(new javax.swing.JFrame(), true);
        helpDialog.setVisible(true);

    }//GEN-LAST:event_helpMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed

        AboutDialog aboutDialog = new AboutDialog(new javax.swing.JFrame(), true);
        aboutDialog.setVisible(true);

    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed

        System.exit(0);
        
    }//GEN-LAST:event_jMenuExitActionPerformed

    public void SetMessagesLogsInJPanelOfTheInterface(String message) {
        
        messageJTextLogServer = logServer.getText();
        messageJTextLogServer += message; 
        logServer.setText(messageJTextLogServer);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem disclaimerMenuItem;
    private javax.swing.JMenuItem helpMenuItem;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea logServer;
    // End of variables declaration//GEN-END:variables
}
